server:
  port: 12222
  error:
    include-binding-errors: always
    include-message: always
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  address: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    hikari:
      maximum-pool-size: 1
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:mydb.db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  cache:
    type: caffeine
  jackson:
    serialization:
      write-dates-as-timestamps: true
cache:
  caches:
    - name: instanceCache
      expire-after-write: 30m
      expire-after-access: 10m
    - name: httpRequestStatisticsCache
      expire-after-write: 30m
      expire-after-access: 10m
    - name: instanceHealthCache
      expire-after-write: 10m
    - name: applicationHealthCache
      expire-after-write: 10m
    - name: instanceAbilityCache
      expire-after-write: 30m
      expire-after-access: 10m
    - name: instancePropertyCache
      expire-after-write: 1m
    - name: applicationEffectiveAuthenticationCache
      expire-after-write: 30m
      expire-after-access: 10m
    - name: folderEffectiveAuthenticationCache
      expire-after-write: 30m
      expire-after-access: 10m
    - name: instanceSystemPropertiesCache
      expire-after-write: 30m
      expire-after-access: 10m
    - name: instanceSystemEnvironmentCache
      expire-after-write: 30m
      expire-after-access: 10m
    - name: applicationDisableSslVerificationCache
      expire-after-write: 30m
      expire-after-access: 10m
    - name: ruleInstanceAssociationCache