name: Generate Daemon TypeScript

on:
  pull_request:
    branches:
      - master
    paths:
      - daemon/**
      - .github/workflows/generate-daemon-typescript.yml

jobs:
  generate-typescript:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('daemon/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Generate typescript
        working-directory: daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew generateTypeScript
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'app/src/common/generated_definitions.d.ts'
          default_author: github_actions
          message: 'Update TypeScript definitions [skip ci]'