name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run jdk:download
          npm run build

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux
  update-website:
    runs-on: ubuntu-latest
    needs: publish
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          repository: krud-dev/ostara-site
          path: site
          token: ${{ secrets.OSTARA_SITE_GITHUB_SECRET }}
      - name: Update website URL
        run: |
          PACKAGE_VERSION=$(cat release/app/package.json | jq -r '.version')
          echo "Version is $PACKAGE_VERSION"
          cd site/assets/js/data
          echo "const version = '$PACKAGE_VERSION';" > version.js
          git config --global user.email "ops@krud.dev"
          git config --global user.name "krud.dev Ops"
          git add version.js
          git diff --quiet && git diff --staged --quiet || git commit -am 'chore: update version'
          git push

