
name: Release Charts

on:
  push:
    # branches:
    #   - master
    paths:
      - helm/**/Chart.yaml
      - .github/workflows/publish-helm.yml
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "ops@krud.dev"
          git config --global user.name "krud.dev Ops"

      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"