name: Publish

on:
  push:
    paths:
      - daemon/**
      - app/**
      - demo/**
      - package.json
      - package-lock.json
      - .github/workflows/publish.yml
  
jobs:
  publish:
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - id: determine-version
        uses: ./.github/actions/determine-version
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install and build
        env:
          VERSION: ${{ steps.determine-version.outputs.version }}
          ORG_GRADLE_PROJECT_version: ${{ steps.determine-version.outputs.version }}
        run: |
          cd app
          npm install
          npm run postinstall
          npm run jdk:download
          npm run build

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd app
          npm exec electron-builder -- --publish always --win --mac --linux