name: Test Spring Client

on:
  push:
    branches:
      - master
    paths:
      - spring-client/**
      - .github/workflows/test-spring-client.yml
  pull_request:
    branches:
      - master
    paths:
      - spring-client/**
      - .github/workflows/test-spring-client.yml

jobs:
  test-spring-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('spring-client/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        working-directory: spring-client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test sonarqube --info
      - name: Publish Test Report - Agent
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
