name: Test Daemon

on:
  push:
    branches:
      - master
    paths:
      - daemon/**
      - .github/workflows/test-daemon.yml
  pull_request:
    branches:
      - master
    paths:
      - daemon/**
      - .github/workflows/test-daemon.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Test Daemon
        run: |
          cd daemon && ./gradlew test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: daemon/build/reports/jacoco/test/jacocoTestReport.xml
          flags: daemon
          fail_ci_if_error: true
