name: Test

on:
  push:
    paths:
      - daemon/**
      - .github/workflows/test-daemon.yml
  pull_request:
    paths:
      - daemon/**
      - .github/workflows/test-daemon.yml

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Test Daemon
        run: |
          cd daemon && ./gradlew test
