name: Update Website

on:
  release:
    types: [published]

jobs:
  update-website:
    runs-on: ubuntu-latest
    needs: publish
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          repository: krud-dev/ostara-site
          path: site
          token: ${{ secrets.OSTARA_SITE_GITHUB_SECRET }}
      - name: Update website URL
        env: 
          PACKAGE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "Tag name is $PACKAGE_TAG_NAME"
          PACKAGE_VERSION=$(echo $PACKAGE_TAG_NAME | sed 's/v//')
          echo "Version is $PACKAGE_VERSION"
          cd site/assets/js/data
          echo "const version = '$PACKAGE_VERSION';" > version.js
          git config --global user.email "ops@krud.dev"
          git config --global user.name "krud.dev Ops"
          git add version.js
          git diff --quiet && git diff --staged --quiet || git commit -am 'chore: update version'
          git push